### PR TITLE
ci: Add windows

### PR DESCRIPTION
**Pull request by wael-sadek**

### CODE REVIEW

**Comment by wael-sadek** [comment]
@maelle , Please remember to use the below paths for windows 
```
C:\Program Files\Microsoft MPI\Bin;
C:\Program Files\GDAL;
C:\taudem"
```

**Comment by maelle** [comment]
@wael-sadek on GitHub Actions do you know how to set up different environment variables depending on the OS? Or could the workflow add the variables to the path?

**Review by maelle — CHANGES_REQUESTED** [review]
Thank you!

I see R can't find GDAL. It uses `gdal-config --version` and `gdalinfo --version` if it fails. What is the correct Windows command?

**Comment by wael-sadek** [comment]
> @wael-sadek on GitHub Actions do you know how to set up different environment variables depending on the OS? Or could the workflow add the variables to the path?

Yes, env can be defined per job.

**Pull request merged**
